feat: add check and set label action

diff --git a/.github/workflows/generate-release-pull-request.yaml b/.github/workflows/generate-release-pull-request.yaml
--- a/.github/workflows/generate-release-pull-request.yaml
+++ b/.github/workflows/generate-release-pull-request.yaml
@@ -14,6 +14,9 @@ on:
       REVIEWER:
         required: false
         type: string
+      LABELS:
+        required: false
+        type: string
     secrets:
       gh_app_id:
         required: true
@@ -41,6 +44,33 @@ jobs:
         run: echo "CURRENT_DATETIME=$(date +"%Y-%m-%dT%H:%M:%S%z")" >> $GITHUB_ENV
         env:
           TZ: 'Asia/Tokyo'
+      - name: Check and Set pull request label options
+        id: set-label
+        run: |
+          labels=${{inputs.LABELS}}
+          # カンマで分割して配列に格納
+          IFS=',' read -r -a labels <<< "$label_names"
+
+          pr_create_label_options=''
+          pr_edit_label_options=''
+          for label in "${labels[@]}"; do
+              echo "$label"
+              # 不要な先頭および末尾の空白を削除しつつ表示
+              label_name=$(echo "$label" | awk '{$1=$1};1')
+              echo $label_name
+              if ! $(gh label list -R "$GITHUB_REPOSITORY" --json name | jq ". | any(.name == \"${label_name}\")"); then
+                #=> ラベルが存在しなかった場合にはエラー表示
+                echo "::error title=${label_name} is not found::Please create a new label"
+              fi
+              pr_create_label_options+="--label '${label_name}' "
+              pr_edit_label_options+="--add-label '${label_name}' "
+          done
+
+          echo $pr_create_label_options
+          echo "PR_CREATE_LABEL_OPTIONS=$pr_create_label_options" >> $GITHUB_OUTPUT
+
+          echo $pr_edit_label_options
+          echo "PR_EDIT_LABEL_OPTIONS=$pr_edit_label_options" >> $GITHUB_OUTPUT
       - name: Generate pull request
         run: |
           set -eu
@@ -51,11 +81,11 @@ jobs:
           if [[ -z "$SAME_PR_COUNT" ]]; then
             #=> 同じブランチ名のプルリクエストがない場合はプルリクエストを新規作成する
             ghcp empty-commit -r $GITHUB_REPOSITORY -b release/$RELEASE_VERSION -m 'chore: empty commit to open follow up pull request'
-            gh pr create -B $GITHUB_REF_NAME -H release/$RELEASE_VERSION --title "$RELEASE_VERSION ${{env.CURRENT_DATETIME}}" --body "$CHANGELOG" --reviewer "${{inputs.REVIEWER}}" --milestone "$RELEASE_VERSION" --label Release
+            gh pr create -B $GITHUB_REF_NAME -H release/$RELEASE_VERSION --title "$RELEASE_VERSION ${{env.CURRENT_DATETIME}}" --body "$CHANGELOG" --reviewer "${{inputs.REVIEWER}}" --milestone "$RELEASE_VERSION" ${{steps.set-label.outputs.PR_CREATE_LABEL_OPTIONS}}
           else
             #=> 同じブランチ名のプルリクエストがある場合は該当のプルリクエストを編集する
             SAME_PR_NUMBER=$(gh pr list -B $GITHUB_REF_NAME -H release/$RELEASE_VERSION --json 'number' --jq '.[].number')
-            gh pr edit $SAME_PR_NUMBER --title "$RELEASE_VERSION ${{env.CURRENT_DATETIME}}" --body "$CHANGELOG" --milestone "$RELEASE_VERSION" --add-label Release
+            gh pr edit $SAME_PR_NUMBER --title "$RELEASE_VERSION ${{env.CURRENT_DATETIME}}" --body "$CHANGELOG" --milestone "$RELEASE_VERSION" ${{steps.set-label.outputs.PR_EDIT_LABEL_OPTIONS}}
           fi
         env:
           GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
